[package]
name = "askpass-curses"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
derive_builder = "0.20.2"
lazy_static = "1.5.0"
libc = "0.2.174"
pancurses = { version = "0.17.0", features = ["win32a"] }
